### PR TITLE
Changed modifiers to more closely match Chrome's behavior

### PR DESCRIPTION
**Pull request by viveksjain**
`Cmd/Ctrl+Enter` now opens the link in a new tab, `Shift+Enter` opens it in a new window, and `Cmd/Ctrl+Shift+Enter` opens it in a new tab and switches to it.

### CODE REVIEW

**Comment by chetan51** [comment]
Sweet, thanks!

Unfortunately, the behavior is not quite correct on Windows Chrome. I'll have to fix and test that before I can push an update.

**Comment by viveksjain** [comment]
Hmm okay let me know what the problem is when you find it. As far as I can tell, all the code does is check what keys you are pressing, and then presses those same keys when opening the link.

**Comment by chetan51** [comment]
After a cursory glance, looks like the modifier keys do different things on different platforms, so maybe we have to simulate different keys after checking the platform.

**Comment by chetan51** [comment]
Pushed in the latest update (1.8).

**Pull request merged**
